### ISSUE TITLE
org.bukkit.command.CommandException: Cannot execute command 'tardis' in plugin TARDIS v4.0.6-b1815 - plugin is disabled

### ISSUE THREAD

**Issue by SiebeJwz** [eccentricdevotion/TARDIS#102]
Server is running Spigot 1.13.2
Worldguard Legacy 7.0.0 beta 03
Error log: https://pastebin.com/wsxmjfB9

"org.bukkit.command.CommandException: Cannot execute command 'tardis' in plugin TARDIS v4.0.6-b1815 - plugin is disabled"

**Comment by eccentricdevotion** [comment]
Need to see the entire log, its not surprising you get an error trying to run a TARDIS command if the plugin is disabled. The server log will have given a reason why the plugin is disabled at the beginning of the server startup process...

**Comment by eccentricdevotion** [comment]
Did you also install TARDISChunkGenerator?

**Comment by NABrr** [comment]
I have a similar issue. Logs state that an incorrect version of WorldGuard is installed even though I worked fine before. This seemed to only start happening to me after updating to a more recent build of 1.13.2 Paper. I believe it's only one release behind current last I checked. Before that I had the same versions of the plugins they're having issues with. I have TARDISChunkGenerator installed as well. I had tried updating to the release candidate for WorldGuard but went back to Beta 3 after it failed to start and caused other plugins to fail because of it. I also have WorldEdit Beta 5. I'm currently out and typing on my phone. I could find a log to show you once I'm at my computer if needed. It's just strange that it worked perfectly before but now refuses to start in spite of having a 7.0.0 build of WorldGuard.

**Comment by eccentricdevotion** [comment]
@NABrr yes a log file would be good to see

**Comment by NABrr** [comment]
[latest.log](https://github.com/eccentricdevotion/TARDIS/files/3193596/latest.log)
Here is a really long log file. Apologies, and I don't know why there's the spam of vote errors.... but TARDIS is hiding in there somewhere <-< >->

**Comment by eccentricdevotion** [comment]
Problems:
1. You have both FastAsyncWorldEdit _and_ WorldEdit on the server
2. FastAsyncWorldEdit has a different version number format than WorldEdit (but is still identified as "WorldEdit" - TARDIS sees FAWE as WorldEdit and sees / thinks that the version number is wrong so disables itself.

Solution: 
1. Remove the WorldEdit jar (I presume you want to use FAWE...)
2. Unzip the FAWE jar file, edit the version number in the plugin.yml file (1.13.110 -> 7.0.0), re-zip and change the file extension back to .jar

This was fixed in ead559a for TARDIS 4.1

**Comment by NABrr** [comment]
My bad then. The documentation for FAWE didn't clearly state if it was an extension to WorldEdit or if it was a standalone thing. Thanks for the troubleshooting!
