### ISSUE TITLE
MySQL table doesnt exist

### ISSUE THREAD

**Issue by LozoTrioxide** [eccentricdevotion/TARDIS#124]
**Describe the bug**
Console error saying 'Table 'trioxide_servers.blocks' doesn't exist' 

**To Reproduce**
Steps to reproduce the behaviour:
I was using the NWSE button to rotate my tardis when it happens

**Screenshots**
I dont have any screenshots that'd really show the issue, sorry

**Log files**
https://pastebin.com/RdtQheB5

**Comment by LozoTrioxide** [comment]
This is where ive told the tardis to land if it helps at all
![image](https://user-images.githubusercontent.com/50601395/66229431-b4601c00-e6d9-11e9-92e1-4e4beb1e8a13.png)

**Comment by mrcoffee1026** [comment]
The very first thing I'd check out is that your credentials are correct in plugins/TARDIS/config.yml... first bit that sets up the database access:
```
# config file
debug: false
storage:
  database: mysql
  mysql:
    url: mysql://localhost:3306/TARDIS
    user: yourdbusername
    password: yourdbpassword
    prefix: t4s_

```
I believe you would get this error if you have not set up this database on your server first or also if you're using a mode other than specified (I can't recall the other options but one creates a .db file on the server... if that is missing, this error would also occur).  If you're using mysql for database storage, making an initial empty database with the credentials you supplied in this file should resolve the issue the next time you restart... but what is being used for storage right now is more important to sort out since that information will be lost if you change things here without backing that up first (either the file or previous database contents).

**Comment by LozoTrioxide** [comment]
The database is correct as its got every other table inside the db, also i just checked but the table tardis_blocks does infact exist in the DB 
![image](https://user-images.githubusercontent.com/50601395/66231935-9a293c80-e6df-11e9-8317-fe2eea28db1c.png)

**Comment by eccentricdevotion** [comment]
Should be fixed in build 1910 on the TARDIS Jenkins server

**Comment by LozoTrioxide** [comment]
Thanks, ill check it out :)
