### ISSUE TITLE
Task #1467998 for TARDIS v4.2-b1921 generated an exception

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#128]
**Describe the bug**
Just starts flooding the console with this error, doesn't seem to be a reason for it... recently restarted.  No issue up until it started.

**To Reproduce**
Steps to reproduce the behaviour:
Just run and wait, I guess?

**Screenshots**

**Log files**
https://pastebin.com/dmzenmFg

**Comment by eccentricdevotion** [comment]
Gallifreyan structures are spawning too often and too close together. This results in spawner blocks being overwritten before they can be set to spawn villagers...
I have changed the code so that there is a minimum delay between building a structure. This should make Gallifreyan buildings more rare and hopefully get rid of the errors.
Build 1922.

**Comment by mrcoffee1026** [comment]
excellent thanks!
