### ISSUE TITLE
[Question] TARDIS & Bees

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#185]
It looks like bees, by design, don't come out at night. But the TARDIS world is always night. Is there a way to change that so somebody could farm bees inside the TARDIS? 

Also, how does the Apiary room work if the world is always night?

**Comment by DaddyElf** [comment]
In the config.yml  
creation: keep_night: true 
change that to false ;)

**Comment by PrincessRTFM** [comment]
My bees are definitely doing _something_ because I come back to my apiary now and then and get honey.

**Comment by Zacatero** [comment]
> In the config.yml creation: keep_night: true change that to false ;)
But @DaddyElf does this only effect TARDIS's as they're created? Or also already existing ones?

**Comment by PrincessRTFM** [comment]
It affects the `TARDIS_TimeVortex` world, so that the plugin stops resetting time to evening whenever it reaches morning. It'll affect all TARDISes.

**Comment by Zacatero** [comment]
One last question, and this may seem stupid.. but does this also mean that the sun would rise visibly? or just logically?

**Comment by PrincessRTFM** [comment]
Depends what you mean by "visibly" there. Yes, the sun will physically rise in the `TARDIS_TimeVortex` world. In an ordinary TARDIS, that's irrelevant because you'll never see outside it. In the Junk TARDIS, it might be visible, I don't know. If you don't have the Junk TARDIS enabled, nobody will ever see the sun, although client-sided mods will still see the world time going through the day.

**Comment by Zacatero** [comment]
Gotcha

**Comment by eccentricdevotion** [comment]
You don't need to set `keep_night` this issue was already sorted when the Apiary room was implemented...
If you look deeper in into the TARDIS config you will see a new setting:
`preferences.wake_bees: [true|false]`
The plugin runs a periodic task to wake bees in the Apiary room so that they come out of their hives and collect pollen. The bees have a `setCannotEnterHiveTicks` setting which is set high enough that they won't immediately go back into their hives at night.

**Comment by Zacatero** [comment]
but @eccentricdevotion does that only work inside the Apiary room? Or everywhere in the TARDIS? For example if we were to have hives/bees not in the apiary room?

**Comment by eccentricdevotion** [comment]
Like other farming rooms in the TARDIS, it is specific to the Apiary room. Hives/Bee nests can be anywhere in the room for the bees to be woken.

**Comment by PrincessRTFM** [comment]
Hm. Does that also mean that only _one_ Apiary room will do that? Does it track the Apiary room like it does (did?) for the Village room or does it load the ARS configuration and find _all_ Apiary rooms?

Also... is it possible to control where the bees come out from their hives/nests? Because a couple of times I've had them spawn in adjacent rooms (or maybe they managed to operate the pressure plates and flew out?) and had to leash them to get them back in.

**Comment by eccentricdevotion** [comment]
- Just the one room
- I'm pretty sure they can trigger pressure plates (which I find a bit odd)

**Comment by PrincessRTFM** [comment]
Well, I did the same thing as with my Village room and replaced the plates in the room with buttons. Followup, can non-player entities use the gravity wells? Because if not, that's a perfect fallback gate for any entities that might escape.
