### ISSUE TITLE
Cannot farm my pet parrots

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#211]
**Describe the bug**
I have a birdcage room. I even jettisoned and regrew it, after the first time the plugin told me I didn't have one, which I did. But when I enter with my two pet parrots nearby, they show up in the console and I get a message about needing to grow a BIRDCAGE room to farm parrots.

Also, while inside my TARDIS, I can't get my parrots _off_ my shoulders.

**To Reproduce**
Grew a BIRDCAGE, had a pair of pet parrots on the ground next to my TARDIS, entered. No server log messages are ever generated. Using b2002 with `Paper version git-Paper-102 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Comment by eccentricdevotion** [comment]
Hmmm, not having any trouble farming parrots, either tamed or untamed.
Tamed pets, parrots included, are always teleported to the console.
Untamed parrots are sent to the birdcage.
Parrots not unmounting - because spawning is restricted in the TARDIS world, the parrot needs to be despawned from the shoulder and respawned on the ground and the plugin is currently preventing this. Fixed in next build.

**Comment by PrincessRTFM** [comment]
Oh, pets always go to the console? I guess that'd be what was happening there, although the message about not having a BIRDCAGE room confused me. That might be a bug at least.

**Comment by eccentricdevotion** [comment]
8ed0b97
