### ISSUE TITLE
HADS Displacement Infinite Loop

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#258]
**Describe the bug**
When you punch a tardis enough that it activates hads, and then keep punching, it activates multiple times, and if you don't notice or are lagging or are mean, you activate it so many times that it never stops sending cloister bell messages

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate HADS and Displacement on a TARDIS
2. Punch the TARDIS as much as possible, as quickly as possible, and don't stop when HADS activates
3. Wait for the TARDIS to demat
4. See chat spammed with infinite Cloister Bell messages

**Screenshots**
https://i.imgur.com/1V769cs.png

**Comment by roberestarkk** [comment]
Actually I've just checked it again and you don't need to keep punching it, it just does it a bunch of times anyway

**Comment by Chew** [comment]
I ran a timings report to see what's going on, and I've found the cause, but no idea how to fix it.

What happens is, every time you hit the TARDIS, it calls the TARDISBlockDamageListener, and when it hits the damage limit, it runs this line right here
https://github.com/eccentricdevotion/TARDIS/blob/f1842c7fd25b101ba2841f1c2352fae1a55553be/src/main/java/me/eccentric_nz/TARDIS/listeners/TARDISBlockDamageListener.java#L93
This response takes about 600 ms for me (because it's in-sync, so the entire code has to execute before it can continue), leaving plenty of time to be spammed.
The code to check whether it should actually do stuff related to hads is here:
https://github.com/eccentricdevotion/TARDIS/blob/f1842c7fd25b101ba2841f1c2352fae1a55553be/src/main/java/me/eccentric_nz/TARDIS/listeners/TARDISBlockDamageListener.java#L83
!plugin.getTrackerKeeper().getInVortex().contains(id) is the notable thing here. While the code line 93 executes does put it in the vortex, it doesn't do it fast enough, allowing this to remain true.

Again, no idea how to fix this though. I've had this problem before too.

[My timings report](https://timings.spigotmc.org/?url=ozudofosik)

**Comment by Chew** [comment]
Found the REAL issue...

https://github.com/eccentricdevotion/TARDIS/blob/0802ea5f713e185edd6757807bdafd42942f9d28/src/main/java/me/eccentric_nz/TARDIS/hads/TARDISHostileDisplacement.java#L76

This for loop is executing way more than it should.

**Comment by eccentricdevotion** [comment]
Hopefully didn't break anything else...
