### ISSUE TITLE
/tardisadmin spawn_abandoned 

### ISSUE THREAD

**Issue by Rocologo** [eccentricdevotion/TARDIS#309]
**Describe the bug**
After installing B2170 I can now enter the spawned TARDIS, but Im still having problems.
1) First time I enter the TARDIS a lot if items spawn immidiately.... Buttons, Signs, redstone stuff. It looks like all you control buttons spawn in the TARDIS

![Screenshot from 2020-07-19 11-02-33](https://user-images.githubusercontent.com/1008133/87871281-66d64680-c9af-11ea-998d-ee7259544e3d.png)

2) When I want to claim the TARDIS I click on the woodon butten and turn on the CAPACITOR, but the TARDIS is not claimed until I turn it off again. ??? When I tested with seed blocks yesterday, I only had to turn on the CAPACITOR??? 
3) I the turn the capacitor on again and try to use other buttons, but worldguard says Im not allowed. 
![Screenshot from 2020-07-19 10-34-26](https://user-images.githubusercontent.com/1008133/87870847-07c30280-c9ac-11ea-9426-d6c4d73f06d9.png)

![Screenshot from 2020-07-19 10-43-45](https://user-images.githubusercontent.com/1008133/87870928-d0a12100-c9ac-11ea-86c1-0e3758f06f6c.png)

4) and because i ran out of enegy I wanted to add 64 diamonds to the capacitor dispenser, but I was not able to open the chest, because I had not claimed the TARDIS and I could not claim the TARDIS because I had not energy to turn on the capacitor.
I had to add the flag "Chest access" before I could add diamonds so I could claim the TARDIS
![Screenshot from 2020-07-19 11-05-38](https://user-images.githubusercontent.com/1008133/87871356-f11eaa80-c9af-11ea-9983-ec85f6d50fff.png)

5) I also notice that the spawned position is wrong. When I use
/tardisadmin spawn_abandoned [SCHEMATIC] [PRESET] [DIRECTION] world x y z
This is what I entered **/tardisadmin spawn_abandoned ELEVENTH FACTORY NORTH flat -276 3 -665** 
the z coordinate is not the one I enter, but the one where I look and I get a policebok made of blue wool and not the grey FACTORY one
![Screenshot from 2020-07-19 10-54-02](https://user-images.githubusercontent.com/1008133/87871121-2d510b80-c9ae-11ea-9d0f-2649f0d8062a.png)
.

**Comment by Rocologo** [comment]
6) anothe rbus is when I spawn this one

/tardisadmin spawn_abandoned ELEVENTH POLICE_BOX_BLUE_OPEN NORTH flat -264 3 -665

The TARDIS does not work and I cant enter

![Screenshot from 2020-07-19 11-50-43](https://user-images.githubusercontent.com/1008133/87872124-57a6c700-c9b6-11ea-8314-5c672a5c71a1.png)
But if I instead spawn this one with closed door, 
![Screenshot from 2020-07-19 11-51-16](https://user-images.githubusercontent.com/1008133/87872136-69886a00-c9b6-11ea-859b-b548d6dd7b3c.png)
And I can open the door, but when I try close the I get the message that I cant closed an abandoned TARDIS with is okay, but I also get a permission warning, which I dont know what means... look at the picture.

**Comment by Rocologo** [comment]
One last thing :-) 

The tardisgive SEED command

https://eccentricdevotion.github.io/TARDIS/give-commands.html

is not really documentet and it seens not like I have the posibillty to set PRESET when creating a SEED ? (Or at least I dont know how to choose **POLICE_BOX_BLUE** f.ex. I only get a list of Materials but I dont know how to translate the materials to f.ex POLICE_BOX_BLUE.

**Comment by eccentricdevotion** [comment]
1. Items in TARDIS will be from the TARDIS that previously occupied the same spot. There were changes to Spigot from a few versions ago that made it hard to efficiently remove large areas of blocks by resetting the chunk. I probably need to come up with a new solution, although it seems to work OK if the chunk is loaded by being present in it...
2. Need to do more testing...
3. Need to do more testing...
4. There is no energy requirement needed to claim a TARDIS, so I'm guessing that's not the real issue here. I can access the Artron Condenser chest (when de-opped) without needing to set the 'chest_access' flag.
5. Specifying coordinates for spawning a TARDIS was added so it could be done from the console, _if run by a player it always uses the targeted location_
6. The `POLICE_BOX_BLUE_OPEN` preset shouldn't be the tab list, it'll be removed in the next build...
7. You can't specify a preset for seed blocks, the materials are for the floor/walls

**Comment by eccentricdevotion** [comment]
Please include output of `/tardis version`

**Comment by eccentricdevotion** [comment]
1. ...
2. Fixed
3. Fixed
4. Fixed
5. ...
6. Fixed
