### ISSUE TITLE
Instant crash when using tardis (1.16.2)

### ISSUE THREAD

**Issue by Killma** [eccentricdevotion/TARDIS#335]
**Describe the bug**
when using tardis the server crash 

**To Reproduce**
Steps to reproduce the behaviour:
1: try to use, delete or create tardis.
2: server crash when tardis spawn

**Log files**
https://pastebin.com/ckfs3YKU

**`/tardis version` output**
[14:53:32] [Server thread/INFO]: [TARDIS] Server version: git-Spigot-379750e-43c7ff9 (MC: 1.16.2)
[14:53:32] [Server thread/INFO]: [TARDIS] TARDIS version: 4.5-b2185
[14:53:32] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.5
[14:53:32] [Server thread/INFO]: [TARDIS] Multiverse-Core version: 4.1.0-b775
[14:53:32] [Server thread/INFO]: [TARDIS] Essentials version: 2.18.0.21
[14:53:32] [Server thread/INFO]: [TARDIS] WorldGuard version: 7.0.4-beta1;bc551da
[14:53:32] [Server thread/INFO]: [TARDIS] TARDISWeepingAngels version: 3.3.3
[14:53:32] [Server thread/INFO]: [TARDIS] LibsDisguises version: 10.0.15

**Comment by eccentricdevotion** [comment]
Cannot reproduce.
Please make sure that your server is actually starting up without errors before reporting a bug.

**Comment by eccentricdevotion** [comment]
Spigot bug
https://hub.spigotmc.org/jira/browse/SPIGOT-6076

**Comment by Killma** [comment]
this without uncompatible plugin in this file I juste move my tardis
https://pastebin.com/vzp9jJYV

**Comment by Chew** [comment]
Remove TARDIS/TCG and see if it boots fine.

**Comment by Killma** [comment]
without tardis
https://pastebin.com/Ws98X1SU

**Comment by eccentricdevotion** [comment]
This is most likely a plugin conflict, I would suspect maybe AsyncWorldEdit which injects classes into the server (effectively making it a non-standard server jar). From your log there is not yet a proper AsyncWorldEdit 1.16.2 adaptor.
I suggest you do a search search to determine if that is the case yourself. Enable TARDIS with half your current plugins, if the problem persists, enable the other half and check again. If the problems gone, then it's one of the plugins from the first group. Add half of the plugins to the mix and repeat the process.
If you can reproduce this on a standard unaltered server, I'll look into it further.

**Comment by jpg39** [comment]
I have the same issue, but I have no other plugins installed on my server.

**Comment by eccentricdevotion** [comment]
@jpg39 server log?

**Comment by jpg39** [comment]
> @jpg39 server log? Doing what exactly?

As soon as the TARDIS is entered, the server immediately closes. 

16.08 01:37:23 [Server] Server thread/ERROR Encountered an unexpected exception
16.08 01:37:23 [Server] INFO net.minecraft.server.v1_16_R2.ReportedException: Exception ticking world
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1117) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
16.08 01:37:23 [Server] INFO Caused by: java.lang.NullPointerException
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayOutMultiBlockChange.<init>(SourceFile:34) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:181) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$9(ChunkProviderServer.java:383) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_211]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:378) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:346) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:329) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO ... 5 more
16.08 01:37:23 [Server] Server thread/ERROR Cause of unexpected exception was
16.08 01:37:23 [Server] INFO java.lang.NullPointerException: null
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayOutMultiBlockChange.<init>(SourceFile:34) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:181) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$9(ChunkProviderServer.java:383) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_211]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:378) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:346) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:329) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Spigot_Latest_1.16.2.jar:git-Spigot-379750e-82542d0]
16.08 01:37:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
16.08 01:37:23 [Server] Server thread/ERROR This crash report has been saved to: /./crash-reports/crash-2020-08-16_01.37.23-server.txt

**Comment by eccentricdevotion** [comment]
I can't reproduce this on a fresh server install, but can on an existing server.
Unfortunately there's not much I can do about it until the [Spigot bug](https://hub.spigotmc.org/jira/browse/SPIGOT-6076) is fixed.

**Comment by eccentricdevotion** [comment]
Bug fixed, update Spigot.
