### ISSUE TITLE
Redo Whovian worlds with new 1.16.2 customised worlds

### ISSUE THREAD

**Issue by eccentricdevotion** [eccentricdevotion/TARDIS#336]
BUFFET worlds are no longer supported by Spigot, and there is not yet support for customised worlds - once there is, recode the Skaro, Siluria and Gallifrey worlds to take advantage of the new Minecraft features.

**Comment by eccentricdevotion** [comment]
You should disable the Skaro, Siluria and Gallifrey worlds in _planets.yml_ for now :(

**Comment by eccentricdevotion** [comment]
Custom biomes / worlds seem to load OK, but are terribly laggy
https://hub.spigotmc.org/jira/browse/SPIGOT-5877
https://hub.spigotmc.org/jira/browse/SPIGOT-6073

**Comment by eccentricdevotion** [comment]
[Paper todo - chunk generation seems slow with a lot of it happening](https://github.com/PaperMC/Paper/blob/ee7dce8bdd69ef9f49018fb44534164f4d496075/SHIT_TO_CHECK.md)

**Comment by mrcoffee1026** [comment]
This change does restore the single biome worlds with some glaring issues remaining within them: Time is permanently fixed at 6am (0ticks) for all worlds in spite of the gamerule of DoDayNightCycle being set to true, as a result, instead of limited night spawning in siluria, there are never spawns from those spawners since they have transparent blocks above them and are always in level 15 light.  Structure generations in skaro - in particular - stand out as never checking for ground level and so there are an enormous amount of flying versions of the structures since deserts have many dips below the typical median.  I believe this issue still exists in gallifrey, less obviously for the structures, far more obviously for the tardis itself which very frequently positions itself 20-30 blocks above ground level, particularly if one of the spheres generates at that location as a good portion of the floor below the sphere is removed when it does.  There are "gamerule" settings in the planets.yml file, it would seem that either this only selectively alters the particular settings you have pre-placed there, or these rules are not being applied.  I attempted to preemptively set "announceAdvancements: false" but still had to do this manually to each world after they'd been loaded in.  Really not sure why it takes 2 restarts to reload the planets after they're deleted either, maybe there's some buffet world excuse for this, it just seemed odd to me.

**Comment by eccentricdevotion** [comment]
@mrcoffee1026 
1. Update TARDISChunkGenerator to restore normal day/night cycle, I fixed this a few hours ago
2. Structure generation is on the TODO list already - the code for getting the Y position to build the structure hasn't changed at all, so there is something else going on there... just haven't had time to check yet
3. Will check what's up with gamerules
4. I spent quite a lot of time trying to get a single restart to generate the worlds, but it doesn't seem to be possible with the current Minecraft mechanics - the first restart installs the custom dimension datapacks in the correct location, and even though the plugin/Spigot reloads the datapacks, for some reason the worlds won't generate until the next server restart.

**Comment by eccentricdevotion** [comment]
Custom dimensions are still experimental and not officially supported by Spigot yet...

**Comment by mrcoffee1026** [comment]
I am using Paper, don't know how much difference that will make, but they seem to be in MUCH better shape now, thank you so much!

**Comment by eccentricdevotion** [comment]
Paper is based on Spigot, so no difference at all right now.

I have plans for doing some custom biomes for TARDIS dimensions at some stage, so that we can change the sky colour and make custom trees etc instead of relying on resource pack switching which is really slow...
