### ISSUE TITLE
tardis repair

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#357]
**Describe the bug**

in a new spawn tardis ( iron ) i went to change to a new console and it said i couldnt bc the damage was to great. i needed ( 7 blue wool with blue wool never being used, 1 note_block and 1 jukebox even knowing the storage and advance systems are in their spawn location 
0

**To Reproduce**
grow new iron
charge and change console ( iron to iron ) to change wall and floor types
couldn't due to damage

**`/tardis version` output**

> [17:23:52] [Server thread/INFO]: [TARDIS] Server version: git-Spigot-b5a13e6-927200a (MC: 1.16.2)
> [17:23:52] [Server thread/INFO]: [TARDIS] TARDIS version: 4.5-b2189
> [17:23:52] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.5
> [17:23:52] [Server thread/INFO]: [TARDIS] LibsDisguises version: 10.0.16-SNAPSHOT
> [17:23:52] [Server thread/INFO]: [TARDIS] Essentials version: 2.18.1.0
> [17:23:52] [Server thread/INFO]: [TARDIS] WorldGuard version: 7.0.3;5407315
> [17:23:52] [Server thread/INFO]: [TARDIS] TARDISWeepingAngels version: 3.3.2
> [17:23:52] [Server thread/INFO]: [TARDIS] GriefPrevention version: 16.14.0

**Comment by eccentricdevotion** [comment]
What related config settings do you have?

**Comment by eccentricdevotion** [comment]
Upgrade scanner was comparing `VOID_AIR` to `AIR`...

**Comment by Airomis** [comment]
100%

**Comment by eccentricdevotion** [comment]
If you mean `100%` for the `desktop.block_change_percent`, you probably want the opposite - `100%` would mean that the amount of blocks that _have been changed_ from the original schematic is 100%, I presume you want there to be the same blocks as the original schematic, so 0% would be better, but that seems unrealistic to me, as then even minor customisation of the console would make the process fail - which is why it is set to a reasonable 25% by default...

If you mean `100%` bug fixed, then please close the issue...
