### ISSUE TITLE
Server refusing to start?

### ISSUE THREAD

**Issue by RazihelYT** [eccentricdevotion/TARDIS#489]
I am unable to give any proper information except for I am running the latest version of Paper 1.16.5, TARDIS, TARDISChunkGenerator, and Multiverse Core. I have been told by my server host that this [error](https://dev.bukkit.org/paste/77b753f9) is caused by the tardis plugin. I have tried disabling the plugins, uninstalling them, and even disabling worlds one by one to find the root cause of the situation but have come up empty handed.

**Comment by RazihelYT** [comment]
It seems that the plugin wants to keep creating a world_tardis_skaro world for no apparent reason and is causing the crash, I have no idea how to disable it.

**Comment by Chew** [comment]
I had this issue. Essentially the fix is:

1) Stop your server.
2) Delete the world_name_tardis_skaro folder
2) Go to your main world folder
3) Delete the level.dat_old folder
4) Download level.dat
5) Upload it to an NBT editor (such as https://nbt.mcph.to)
6) Navigate to WordlGenSettings then dimensions
7) Delete any instances of `tardis:` by right-clicking on it and clicking delete
8) Click Save
9) Reupload the level.dat, replacing the current one there
10) Restart your server

**Comment by RazihelYT** [comment]
> I had this issue. Essentially the fix is:
> 
> 1. Stop your server.
> 2. Delete the world_name_tardis_skaro folder
> 3. Go to your main world folder
> 4. Delete the level.dat_old folder
> 5. Download level.dat
> 6. Upload it to an NBT editor (such as https://nbt.mcph.to)
> 7. Navigate to WordlGenSettings then dimensions
> 8. Delete any instances of `tardis:` by right-clicking on it and clicking delete
> 9. Click Save
> 10. Reupload the level.dat, replacing the current one there
> 11. Restart your server

Still no changes, The server wants to keep creating the world_tardis_skaro file for the world and refuses to start. Any additional steps I need to take to resolve the issue?

**Comment by eccentricdevotion** [comment]
The latest Spigot/Paper builds have added support for loading dimensions from data packs. This is something that TARDISChunkGenerator handled before this support was added. In order to avoid conflicts and allow the worlds to load successfully without crashing the server changes have been made to both the TARDIS planet datapacks and the plugin.

This was addressed in #484.

Solution:

1. Roll back the server to a Spigot/Paper build before the dimension support was added (Spigot 3042 / Paper 593)
2. Install the latest TARDIS and TARDISChunkGenerator from the Jenkins server
3. Start the server - TARDIS will update the planet data packs
4. Stop the server
5. Update Spigot / Paper to the latest build
6. Start the server

**Comment by eccentricdevotion** [comment]
Note:
TARDISChunkGenerator will no longer load the "siluria", "gallifrey" and "skaro" worlds. If you have builds in these worlds that you want to keep, you can stop the server and transfer the region files from these worlds to the new "world_tardis_siluria", "world_tardis_gallifrey" and "worldname_tardis_skaro" worlds...
