### ISSUE TITLE
Feature Request: Modifier for structure spawning in TARDIS worlds

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#618]
### Describe the feature request

Some of my players complain that the TARDIS worlds are too busy. 
That the structures spawn too often, and there's so many of them that it doesn't feel like proper Minecraft, but more like a modded server.

Is it possible to be able to tweak how the structures generate, so that they appear less frequently?
Not sure how that'd work with things like Siluria which tessellate the structures together, but I guess the ideal is to have structures be about as frequent as villages, and then internally to that 'group' they'd be a particular 'size'/amount/distancing?

One player mentioned "The new 1.18.2 structure spawning" which is apparently a thing and might be helpful?

Might help with #617 as well...

I don't really have a well defined 'solution' to this feeling they have, but I do agree that the structures are way more prevalent than the sort of sprinkling you'd see in a regular vanilla world.

### Describe alternatives you've considered

I don't think there really is one, except to maybe change the world generator back and forth?

**Comment by eccentricdevotion** [comment]
Yep, this is already part of my plan for TARDIS planets.

**Comment by eccentricdevotion** [comment]
No config setting, but structures now spawn less frequently (I'm using the Minecraft algorithm to determine structure locations), they should be more village like (with some new buildings) and are generated during world generation rather than when the chunk loads (so should be less laggy)
TARDIS v4.10.0 build 2425 and up - TARDISChunkGenerator will need updating as well.
