### ISSUE TITLE
Feature request:Locking chameleon circuits

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#624]
### Describe the feature request

Just simply the ability to land somewhere with an adaptive chameleon circuit then hit a button to lock it so you keep the circuit no matter where you move and then unlock it to change it back to normal

### Describe alternatives you've considered

Adding a section to the chameleon circuit where you can choose different biome presets

**Comment by roberestarkk** [comment]
It'd be cool if you could load the current shell into the Shell room.     
It would allow you to do this (though I've not tried to replicate a submerged option in the shell room, so maybe not entirely this), but it'd also be handy to give you a head-start on modifying an existing predefined shell, or even to re-load your current custom shell if you've accidentally deleted it from the room but haven't changed it yet.

My suggestion for activating that would be a button inside the room itself rather than (or as well as) an option in the Chameleon Circuit GUI, as then you'd have to be looking at what's currently there and be sure you are okay with replacing it...

**Comment by jpg39** [comment]
> 

Super good idea, but how would you prevent players from using this feature to just get certain resources in the chameleon presets?  I suppose it doesn’t matter all that much since “rare” items aren’t really used, but still.
