### ISSUE TITLE
TARDIS landing paradox 

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#626]
### Describe the feature request

Just simply a Tardis landing in another Tardis or itself 

### Describe alternatives you've considered

TARDIS landing in itself

**Comment by eccentricdevotion** [comment]
There has been discussion about this before, back on the old BukkitDev site, but the pages are no longer accessible.
It was decided that this was not a feature that was worth implementing, probably because in the actual Whoniverse it can only happen by accident and would prevent anyone from entering or leaving the TARDIS.

**Comment by Batman2741** [comment]
What about just as a landing error thenOn May 10, 2022 8:25 PM, Eccentric Devotion ***@***.***> wrote:
There has been discussion about this before, back on the old BukkitDev site, but the pages are no longer accessible.
It was decided that this was not a feature that was worth implementing, probably because in the actual Whoniverse it can only happen by accident and would prevent anyone from entering or leaving the TARDIS.

**Comment by eccentricdevotion** [comment]
Not likely to happen anytime soon, unless someone else creates their own fork for it
