### ISSUE TITLE
Tardis Flight noise stuck on repeat

### ISSUE THREAD

**Issue by SupremeMartin** [eccentricdevotion/TARDIS#673]
### Describe the bug

After flying somewhere I have released the handbreak only for the tardis_flight sound to be stuck on repeat, it's often overlapping itself and is a constant noise coming from the handbreak.
It does not matter if I engage the handbreak again, a new tardis_flight  noise is played over the top of the one constantly playing.
I also does not matter if I move the hand break to another spot, or if I disable and then re-enable the sfx using /tardisprefs sfx.
I have not investigated if the sound retains after a server restart, but I do not have that kind of power.
Thanks.

### To Reproduce

Unsure what causes it, likely due to messing with the speed of the travel or another kind of setting.

### Log files

Unable to

### '/tardis version' output

Server version: git-Paper-246 (MC: 1.19.2)
TARDIS version: 4.11.1-b2474
TARDISChunkGenerator version: 4.11.0
PlaceholderAPI version: 2.11.2
LibsDisguises version: 10.0.31
dynmap version: 3.4-828
Essentials version: 2.20.0-dev+15-20011b9
Multiverse-Core version: 4.3.2-SNAPSHOT-b870
WorldGuard version: 7.1.0-SNAPSHOT+2207-741f9e2
Multiverse-Inventories verisions: 4.2.4-SNAPSHOT-b524
CoreProtect version: 21.2
WorldBorder version: 2.1.5
LockettePro version: 2.10.10
Towny version: 0.98.3.0

**Comment by eccentricdevotion** [comment]
- Pretty much impossible to troubleshoot and debug if I don't know how to reproduce...
- The plugin tracks the ID of the repeating task playing the sound, but this has obviously been overwritten with a new ID at some stage during your messing around. Now the plugin can no longer cancel the original task because it has lost the ID.
- Yes, a server restart should fix it as the repeating task playing the sound will be cancelled - currently there is no other way to cancel the task.
- The `tardis_flight` sound from the resource pack isn't actually used in the plugin, it's likely to be the `time_rotor` SFX.

**Comment by eccentricdevotion** [comment]
Should hopefully not happen in the future with build 2478 and higher
