### ISSUE TITLE
High Silurians spawn rates

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#799]
When enabled and on default setting the Silurians have an abundance of spawns as well as tend to spawn ontop of the player. 

I don't know if this would help but maybe have them only spawn inside slime chunks with light level 1 as every time we enter a cave we shouldn't run into them and in the underground areas there is light so maybe use the same spawning as a slime or even have structural areas that can spawn underground for them. Or spawn inside of lush caves

**Comment by eccentricdevotion** [comment]
Spawn rate can be set in monster.yml, as can which worlds they spawn in and how many can be in each world.
The problem is that you're probably the only one on the server and the plugin's silurian spawn code checks for underground players to find a valid spawn point - fewer players are going to make it seem like you're being targeted... The code was changed recently because searching for an underground location is very server intensive, and often led to server lag.
I could add a slime chunk config option though you'd have to get it turned on!

**Comment by Airomis** [comment]
That would be great the server I'm on has about 10 players max and only 3-4
is the highest I've ever seen logged on at a time

**Comment by Airomis** [comment]
is it even possible to auto scale it off of the players online?
