### ISSUE TITLE
Tardis info System

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#885]
### Describe the bug

when opening the planets there seams to be a spill over from a diffrent topic list as it shows items like the acid bucket.

the sonic upgrades and sonic components are they both one of the same dose there need to be both?

### To Reproduce

open the tardis info system sign

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

B 2915

**Comment by eccentricdevotion** [comment]
- The acid bucket and other similar items can only be obtained from planet Skaro, so that's why it is in the _Planets_ section.
- Sonic components are the _circuits_ - you can access the circuit recipes from here
- Sonic upgrades is info about what each sonic upgrade does, and the recipe for the upgrade eg sonic + circuit
